name: 'README with Todoist'
author: Siddharth Shyniben
description: 'Updates README with your Todoist stats'

inputs:
  TODOIST_API_KEY:
    description: 'Your Todoist API Key'
    required: true

  USERNAME:
    description: 'Your GitHub username'
    default: ${{ github.repository_owner }}
    required: false

  README_FILE_PATH: 
    description: 'The path to your README.md file'
    default: "./README.md"
    required: false

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "check-square"
  color: "red"
